less/base/_fonts.less, less/base/_typography.less, less/base/_variables.less
Just a proposal to add text-size class.
@AlexisMontagne @phndiaye @aguadoenzo comments are welcomes.
=> Add text-size style

less/base/_datatables.less, less/base/_navs.less, less/core/_colors.less
WIP
Together with PR#235 and PR#140
https://github.com/upfluence/oss-components/pull/25
https://github.com/upfluence/publishr-admin-web/pull/140
=> White action buttons for tables

less/base/_all.less, less/base/_toastr.less, less/core/_colors.less
Paired with https://github.com/upfluence/facade-web/pull/210
=> Better toast messages

less/base/_navs.less
Works with https://github.com/upfluence/ember-influencer/pull/12
=> Extend nav styling reach for sidepanel + Renesting existing

bower.json, less/core/_fonts.less
Should fix the issue with the Text Book font not being that bold :'(
=> Use GT Eesti as GT Eesti Text Book's bold

less/base/_buttons.less, less/base/_images.less, less/mixins/_buttons.less, less/utilities/_typography.less
These were styles that were in the plugin but belonged here.
=> Social Buttons

less/base/_navs.less
removed first-child etc selectors for compatibility with search.
=> standardize nav bar btns

less/base/_alerts.less, less/base/_buttons.less, less/base/_inputs.less
=> Changes for alerts and inputs

less/layouts/_header.less
=> change the sidebar colors

less/vendor/_summernote.less
=> summernote changes

less/vendor/_modal.less
=> Update modal style

.github/CODEOWNERS, .github/pull_request_template.md, less/base/_datatables.less
Related to: https://github.com/upfluence/backlog/issues/312
When the user opens the workflow column selector, it does not close if the user clicks outside this section. It is necessary to close the column selector if the user clicks outside this section (focus out).
Update CSS in relationship with oss-component
=> OSS : upgrade column selection panel

package.json, yarn.lock
Install countdown.js over https
=> use git+https for countdown.js

less/base/_alerts.stories.mdx
Add documentation for the alerts.
Related : https://github.com/upfluence/backlog/issues/585
=> Add docs for the alerts

less/core/_typography.stories.mdx
Add doc for typography
Related : upfluence/backlog#585
=> Oss: Add doc for typography

less/core/_colors.stories.mdx, less/core/_variables.stories.mdx
Add documentation for less/core/_variables.less
Related to: nothing
=> Add doc for variables

less/base/_all.less, less/base/_toggle-switch.less
CSS for Toggle Switch component
=> Toggle switch

less/utilities/_flex.less
Fixed an issue with alignment using the flex wrapper.
=> Fixed: flex justify-content

less/base/_all.less, less/base/_infinite-select.less, less/utilities/_all.less, less/utilities/_loading.less
Add support for:
* Infinite Select component
* Skeleton loading utility class
=> Add infinite-select css & skeleton loading

package.json
Migrate from FontAwesome 4 to 5.
=> Use Font Awesome5

less/core/_upf-icons.stories.mdx, less/utilities/_flex.stories.mdx
Add flexbox documentation
Related to (nothing)
=> Add flexbox documentation

less/utilities/_flex.less
Fixes flex cross axis alignment
=> Fixed: flex cross axis alignment

less/utilities/_typography.less
Added: text-alignment utility classes
=> Added: text-alignment utility classes

less/base/_all.less, less/base/_borders.less, less/utilities/_all.less, less/utilities/_borders.less
This is to help adding border styles easily to blocks.
=> Add border utility classes (no `border-collie` unfortunately)

less/utilities/_flex.less, less/utilities/_flex.stories.mdx
Adds the gap attribute to our flew wrapper.
=> Added: fx-gap in percentage & pixels + few line of doc

less/utilities/_flex.less
instantiates generator function
=> Added: instantiated generator function

less/base/_infinite-select.less
Split absolute / relative display type and clean up
Related to https://github.com/upfluence/backlog/issues/1107
=> Split absolute / relative display type

less/base/_links.less
Adds some CSS for the base upf-link. This wasn't used anywhere even though the `upf-link--reset` modifier was.
=> Add upf-link css

less/base/_inputs.less
Update style for disabled inputs
=> Update style for disabled inputs

less/base/_buttons.less
Update button size & button skins
=> Update button size & button skins

less/base/_all.less, less/base/_badge.less
=> Add css for badges

less/base/_infinite-select.less, less/utilities/_all.less, less/utilities/_scroll-shadow.less
Add classes for scroll-shadow modifier and update infinite-select
Related to nothing
=> Add classes for scroll-shadow modifier

less/base/_badge.less
Add style for the .upf-badge component.
=> Badge: add css for skins and plain modifiers

less/base/_badge.less, less/mixins/_typography.less, less/utilities/_typography.stories.mdx
Extend the number of `text-ellipsis-*` classes.
=> more ellipsis helper classes

less/utilities/_typography.less
Add text-style-uppercase, use in footer threads stats
Related to https://github.com/upfluence/backlog/issues/1314
=> Add text-style-uppercase

less/base/_buttons.less
Add borderless button style
Related to https://github.com/upfluence/backlog/issues/1237
=> Add borderless button style

less/core-v2/_all.less, less/core-v2/_colors.less, less/upfluence-oss.less
Add new color pallet for OSS Token. Implementation of [OSS Token](https://www.figma.com/file/i92PsCj4g8zHhZ5OsrFAcV/1.0-OSS-Tokens-%E2%9A%AB%EF%B8%8F?node-id=30%3A3)
Related to cooldown
=> Add new color pallet

less/core-v2/_colors.stories.mdx
Add doc for new color pallet
Related to cooldown
=> Add doc for new color pallet

less/core-v2/_colors.stories.mdx
Iterate over colors' tokens to list them :)
=> docs/colors: loop over the available tokens for doc generation

less/core-v2/_variables.stories.mdx
Add docs for core-v2/_variables
Related to
=> Add docs for core-v2/_variables

less/core-v2/_colors.less, less/core-v2/_colors.stories.mdx, less/core-v2/_variables.less, less/core-v2/_variables.stories.mdx, less/core/_variables.less, less/utilities/_grid.less
Update CSS variables for spacing & other QoL additions
=> Update CSS variables for spacing & other QoL additions

less/base/_tags.less, less/core-v2/_variables.less
Update tag class for the new tag component
Related to https://github.com/upfluence/backlog/issues/1684
=> Update class for tag component

less/core-v2/_colors.stories.mdx
Fix coreV2/Colors doc display
Related to https://github.com/upfluence/backlog/issues/1703
=> Fix coreV2/Colors doc display

less/base/_links.less
Add upf-link-base style to use it in HTML `a`
Related to https://github.com/upfluence/cs/issues/297
=> Add upf-link-base style

less/utilities/_flex.less, less/utilities/_flex.stories.mdx
Add `flex-wrap: wrap` class
Related to https://github.com/upfluence/backlog/issues/1705
=> Add flex wrap class
